FROM public.ecr.aws/lambda/python:3.10

# Copy requirements file
COPY api/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt

# Install required packages
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy function code
COPY api/lambda_function.py ${LAMBDA_TASK_ROOT}/

# Set the CMD to your handler
CMD [ "lambda_function.lambda_handler" ]